openapi: "3.0.0"
info:
  title: Pasta
  description: This is a sample server for Pasta
  version: 0.0.1
servers:
  - url: /v1
tags:
  - name: Product
    description: Products
  - name: Meal
    description: Meals
  - name: ShoppingList
    description: ShoppingLists
paths:
  /products:
    get:
      operationId: getProducts
      responses:
        '200':
          description: "Lists all Products"
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/Product"
    post:
      operationId: createProduct
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
        required: true
      responses:
        '200':
          description: "Create Product"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
      tags:
        - Product
  /products/{productId}:
    get:
      operationId: getProduct
      responses:
        '200':
          description: "Get Product"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        404:
          description: 'Does not exist'
    put:
      operationId: editProduct
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
        required: true
      responses:
        '200':
          description: "Edit Product"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        404:
          description: 'Does not exist'
    delete:
      operationId: deleteProduct
      responses:
        '204':
          description: "Delete Product"
      tags:
        - Product
    parameters:
      - in: path
        name: productId
        required: true
        schema:
          type: integer
          format: int64
  /meals:
    get:
      operationId: getMeals
      responses:
        '200':
          description: "Lists all Meals"
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/Meal"
    post:
      operationId: createMeal
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Meal'
        required: true
      responses:
        '200':
          description: "Create Meal"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Meal"
      tags:
        - Meal
  /meals/{mealId}:
    get:
      operationId: getMeal
      responses:
        '200':
          description: "Get Meal"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Meal"
        404:
          description: 'Does not exist'
    put:
      operationId: editMeal
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Meal'
        required: true
      responses:
        '200':
          description: "Edit Meal"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Meal"
        404:
          description: 'Does not exist'
    delete:
      operationId: deleteMeal
      responses:
        '204':
          description: "Delete Meal"
      tags:
        - Meal
    parameters:
      - in: path
        name: mealId
        required: true
        schema:
          type: integer
          format: int64
  /shoppingLists/{shoppingListId}:
    get:
      operationId: getShoppingList
      responses:
        '200':
          description: "Lists a Shopping List"
          content:
            application/json:
              schema:
                  $ref: "#/components/schemas/ShoppingList"
        '404':
          description: "No Shopping List found"
      tags:
        - ShoppingList
      parameters:
        - in: path
          name: shoppingListId
          required: true
          schema:
            type: integer
            format: int64

  /shoppingLists/{shoppingListId}/mergedProductEntries:
    get:
      operationId: getShoppingListMergedProductEntries
      responses:
        '200':
          description: "Lists a Shopping Lists merged product entries from both products and meals"
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/ProductQuantity"
        '404':
          description: "No Shopping List found"
      tags:
        - ShoppingList
      parameters:
        - in: path
          name: shoppingListId
          required: true
          schema:
            type: integer
            format: int64

components:
  schemas:
    Product:
      type: object
      required:
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
    ProductEntry:
      type: object
      required:
        - product
        - quantity
      properties:
        id:
          type: integer
          format: int64
        product:
          $ref: "#/components/schemas/Product"
        quantity:
          $ref: "#/components/schemas/Quantity"
    ProductQuantity:
      type: object
      properties:
        product:
          $ref: "#/components/schemas/Product"
        quantity:
          $ref: "#/components/schemas/Quantity"
    Quantity:
      type: object
      required:
        - amount
        - quantityType
      properties:
        amount:
          type: integer
          format: int64
        quantityType:
          type: string
    Meal:
      type: object
      required:
        - name
        - productEntries
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        productEntries:
          items:
            $ref: "#/components/schemas/ProductEntry"
    ShoppingList:
      type: object
      required:
        - name
        - productEntries
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        meals:
          items:
            $ref: "#/components/schemas/Meal"
        productEntries:
          items:
            $ref: "#/components/schemas/ProductEntry"