openapi: "3.0.0"
info:
  title: Pasta
  description: This is a sample server for Pasta
  version: 0.0.1
servers:
  - url: /v1
tags:
  - name: Product
    description: Products
  - name: Meal
    description: Meals
  - name: ShoppingList
    description: ShoppingLists
paths:
  /products:
    get:
      operationId: getProducts
      responses:
        '200':
          description: "Lists all Products"
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/Product"
      tags:
        - Product
  /meals:
    get:
      operationId: getMeals
      responses:
        '200':
          description: "Lists all Meals"
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/Meal"
      tags:
        - Meal
  /shoppingLists:
    get:
      operationId: getShoppingLists
      responses:
        '200':
          description: "Lists all Shopping Lists"
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/ShoppingList"
      tags:
        - ShoppingList

components:
  schemas:
    Product:
      type: object
      required:
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
    ProductEntry:
      type: object
      properties:
        id:
          type: integer
          format: int64
        product:
          $ref: "#/components/schemas/Product"
        quantity:
          $ref: "#/components/schemas/Quantity"

    Quantity:
      type: object
      properties:
        amount:
          type: integer
          format: int64
        quantityType:
          type: string
    Meal:
      type: object
      required:
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        productEntries:
          items:
            $ref: "#/components/schemas/ProductEntry"
    ShoppingList:
      type: object
      required:
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        meals:
          items:
            $ref: "#/components/schemas/Meal"
        productEntries:
          items:
            $ref: "#/components/schemas/ProductEntry"